from std.testing import assert_equal, assert_false, assert_true
from tsonic_js import JsMap, JsSet


def main() raises:
    var values = JsMap[Float64, Float64]()
    _ = values.set(1, 10)
    _ = values.set(2, 20)
    _ = values.set(1, 11)
    assert_equal(values.js_size(), 2)
    assert_true(values.has(1))
    assert_equal(values.get(1).value(), 11)
    assert_equal(len(values.keys()), 2)
    assert_equal(len(values.values()), 2)
    assert_equal(len(values.entries()), 2)
    assert_true(values.delete(2))
    assert_false(values.delete(2))
    values.clear()
    assert_equal(values.js_size(), 0)

    var left = JsSet[Float64]()
    _ = left.add(1)
    _ = left.add(2)
    _ = left.add(2)
    var right = JsSet[Float64]()
    _ = right.add(2)
    _ = right.add(3)
    assert_equal(left.js_size(), 2)
    assert_true(left.has(1))
    assert_equal(left.union(right).js_size(), 3)
    assert_equal(left.intersection(right).js_size(), 1)
    assert_equal(left.difference(right).js_size(), 1)
    assert_equal(left.symmetric_difference(right).js_size(), 2)
    assert_true(left.is_subset_of(left.union(right)))
    assert_true(left.union(right).is_superset_of(left))
    assert_false(left.is_disjoint_from(right))
    assert_equal(len(left.keys()), 2)
    assert_equal(len(left.values()), 2)
    assert_equal(len(left.entries()), 2)
    assert_true(left.delete(1))
    left.clear()
    assert_equal(left.js_size(), 0)
