from std.testing import assert_almost_equal, assert_equal, assert_false, assert_true
from tsonic_js import *


def main() raises:
    assert_equal(math_abs(-2), 2)
    assert_equal(math_floor(1.9), 1)
    assert_equal(math_ceil(1.1), 2)
    assert_equal(math_trunc(-1.9), -1)
    assert_equal(math_round(1.5), 2)
    assert_equal(math_min(3, 1, 2), 1)
    assert_equal(math_max(3, 1, 2), 3)
    assert_equal(math_pow(2, 3), 8)
    assert_equal(math_sign(-5), -1)
    assert_equal(math_clz32(1), 31)
    assert_equal(math_imul(0x7FFFFFFF, 2), -2)
    assert_almost_equal(math_sqrt(9), 3)
    assert_almost_equal(math_cbrt(27), 3)
    assert_almost_equal(math_hypot(3, 4), 5)
    assert_almost_equal(math_sin(0), 0)
    assert_almost_equal(math_cos(0), 1)
    assert_almost_equal(math_exp(0), 1)
    assert_almost_equal(math_log(MATH_E), 1)
    assert_true(number_is_finite(1))
    assert_true(number_is_integer(1))
    assert_true(number_is_safe_integer(NUMBER_MAX_SAFE_INTEGER))
    assert_true(number_is_nan(Float64(FloatLiteral.nan)))
    assert_false(number_is_finite(Float64(FloatLiteral.infinity)))
    assert_equal(number_parse_int(JsString("ff"), 16), 255)
    assert_equal(number_parse_float(JsString("12.5tail")), 12.5)

    var epoch = JsDate(0)
    assert_equal(epoch.get_time(), 0)
    assert_equal(epoch.get_utc_full_year(), 1970)
    assert_equal(epoch.get_utc_month(), 0)
    assert_equal(epoch.get_utc_date(), 1)
    assert_equal(epoch.get_utc_day(), 4)
    assert_equal(epoch.to_iso_string().to_native_strict(), "1970-01-01T00:00:00.000Z")
    assert_equal(date_parse(JsString("1970-01-01T00:00:01.000Z")), 1000)
    assert_equal(date_utc(1970, 0), 0)
    assert_true(date_now() > 0)
